### ISSUE TITLE
just one day is displayed

### ISSUE THREAD

**Issue by hishambakr** [TouchBoarder/weekdays-buttons-bar#2] opened 2016-04-08 03:12 UTC
Thank you for great work.
 I downloaded demo app and found it just display one day not the all 7 days. please advise

**Comment by TouchBoarder** [comment] 2016-04-09 11:37
The demo available on Google Play or did you compiled it from the repo? If from the repo please check if same bug happens in the Google Play version? Else what version of support library do you use.

**Comment by TouchBoarder** [comment] 2016-04-09 14:02
ok, it looks to be related to the latest support library, I'll have a look at it, but please feel free to have a go at it yourself;)

**Comment by hishambakr** [comment] 2016-04-09 15:48
demo app on google play is working fine.

issue with downloading repository or referencing library using gradle. I tried support liberary v23.1.1 and v23.2.1

I spent several hours to discover the source of issue but I failed. I need it in an important project and your library is the only library that satisfy my need. 

I ended up using a library called "chipView" which is not used for this purpose but I built the week component from scratch :(

By the way, my app is RTL which needs more work from me to support RTL.

Hope you have sometime to check the issue. This will save me a lot of time.

Thank you,
Hisham

**Comment by TouchBoarder** [comment] 2016-04-09 23:12
Thanks for your effort Hisham;), It looks like the issue is with the weekdays items layout parameters, where the width was set to `match_parent` as default, a layout parameter ignored by RecyclerView up until 23.2, changing this to wrap_content will fix it.

quote from: http://android-developers.blogspot.no/2016/02/android-support-library-232.html

> Due to this change, make sure to double check the layout parameters of your item views: previously ignored layout parameters (such as MATCH_PARENT in the scroll direction) will now be fully respected.

QUICK FIX:
so a quick fix for this is to set your own layout for the item where the width param is set to `wrap_content`.

**weekday_framelayout.xml**

```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="match_parent"/>
```

you can easily provide this layout by setting:
`weekdaysDataSource.setWeekdayItemLayoutId(R.layout.weekday_framelayout)`

I'll fix this and updated the library to use WRAP_CONTENT as default.

**Comment by hishambakr** [comment] 2016-04-10 00:33
Many thanks for support. Will try it and waiting your library update.

**Comment by TouchBoarder** [comment] 2016-04-10 00:55
I've pushed the changes;)
`compile 'com.github.TouchBoarder:weekdays-buttons-bar:v1.0.0'
`
I've also changed setWeekdayItemLayout**Id** to setWeekdayItemLayout**Res** for better naming convention.

**Closed as completed** 2016-04-11 03:44 UTC
